version: 2

project_name: test-goreleaser-workflow

before:
  hooks:
    - go mod download

builds:
  - binary: test-goreleaser-workflow
    main: ./
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - windows

archives:
  - formats: [ 'tar.gz' ]
    # Must specify name_template to enable wrap_in_directory feature
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - LICENSE
      - README.md

brews:
  - description: "Software to test goreleaser workflow"
    homepage: "https://github.com/ttl256/test-goreleaser-workflow"
    directory: Formula
    skip_upload: auto
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    extra_install: |
      output = Utils.popen_read("#{bin}/BinaryName completion bash")
      (bash_completion/"BinaryName").write output
      output = Utils.popen_read("#{bin}/BinaryName completion zsh")
      (zsh_completion/"_BinaryName").write output
      output = Utils.popen_read("#{bin}/BinaryName completion fish")
      (fish_completion/"BinaryName.fish").write output
      prefix.install_metafiles
    test: |
      system "#{bin}/golangci-lint --version"
    repository:
      owner: ttl256
      name: homebrew-tap-test-goreleaser-workflow

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
